name: Create Tag, Publish to Pub Dev & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - name: Check TAG Version
        run: |
          echo "TAG VERSION: $GITHUB_REF_NAME"
          echo "TAG VERSION: ${{  github.ref_name }}"
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#          flutter-version: '3.19.5'
#      - name: Install dependencies
#        run: flutter clean --verbose && flutter pub get --verbose
#      - name: Publish to pub.dev
#        run: dart pub publish --force
#        env:
#          PUB_TOKEN: ${{ secrets.PUB_ACCESS_TOKEN }}
      - name: Publish To Pub Dev
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_REFRESH_TOKEN }}
          flutterBranch: 'flutter-3.19-candidate.5'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          
